"""init data

Revision ID: 2fa5d054dcc8
Revises: 
Create Date: 2024-09-21 23:29:00.917405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa5d054dcc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poultry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=30), nullable=False),
    sa.Column('Owner', sa.String(length=30), nullable=False),
    sa.Column('Type', sa.String(length=30), nullable=False),
    sa.Column('LocationPointX0', sa.String(length=30), nullable=False),
    sa.Column('LocationPointY0', sa.String(length=30), nullable=False),
    sa.Column('LocationPointX1', sa.String(length=30), nullable=False),
    sa.Column('LocationPointY1', sa.String(length=30), nullable=False),
    sa.Column('LocationPointX2', sa.String(length=30), nullable=False),
    sa.Column('LocationPointY2', sa.String(length=30), nullable=False),
    sa.Column('LocationPointX3', sa.String(length=30), nullable=False),
    sa.Column('LocationPointY3', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('salon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=30), nullable=False),
    sa.Column('Sourface', sa.String(length=30), nullable=False),
    sa.Column('Hight', sa.String(length=30), nullable=False),
    sa.Column('LocationPointX0', sa.String(length=30), nullable=False),
    sa.Column('LocationPointY0', sa.String(length=30), nullable=False),
    sa.Column('LocationPointX1', sa.String(length=30), nullable=False),
    sa.Column('LocationPointY1', sa.String(length=30), nullable=False),
    sa.Column('LocationPointX2', sa.String(length=30), nullable=False),
    sa.Column('LocationPointY2', sa.String(length=30), nullable=False),
    sa.Column('LocationPointX3', sa.String(length=30), nullable=False),
    sa.Column('LocationPointY3', sa.String(length=30), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('length', sa.String(length=300), nullable=False),
    sa.Column('width', sa.String(length=300), nullable=False),
    sa.Column('high', sa.String(length=300), nullable=False),
    sa.Column('ID_Poultry', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ID_Poultry'], ['poultry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actuator',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=30), nullable=False),
    sa.Column('LocationPointX', sa.String(length=30), nullable=False),
    sa.Column('LocationPointY', sa.String(length=30), nullable=False),
    sa.Column('Type', sa.String(length=30), nullable=False),
    sa.Column('ValueBoundLow', sa.String(length=30), nullable=False),
    sa.Column('ValueBoundHigh', sa.String(length=30), nullable=False),
    sa.Column('Icon', sa.String(length=30), nullable=False),
    sa.Column('Id_Salon', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Id_Salon'], ['salon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=30), nullable=False),
    sa.Column('LocationPointX', sa.String(length=30), nullable=False),
    sa.Column('LocationPointY', sa.String(length=30), nullable=False),
    sa.Column('Type', sa.String(length=30), nullable=False),
    sa.Column('ValueLow', sa.String(length=30), nullable=False),
    sa.Column('Icon', sa.String(length=30), nullable=False),
    sa.Column('ValueHigh', sa.String(length=30), nullable=False),
    sa.Column('ID_Salon', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ID_Salon'], ['salon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_actuator',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Time', sa.DateTime(), nullable=False),
    sa.Column('Value', sa.Numeric(precision=18, scale=0), nullable=False),
    sa.Column('ID_Actuator', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_Actuator'], ['actuator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_sensory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Time', sa.DateTime(), nullable=False),
    sa.Column('Value', sa.Numeric(precision=18, scale=0), nullable=False),
    sa.Column('ID_Sensory', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_Sensory'], ['sensory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_sensory')
    op.drop_table('action_actuator')
    op.drop_table('sensory')
    op.drop_table('actuator')
    op.drop_table('salon')
    op.drop_table('user')
    op.drop_table('poultry')
    # ### end Alembic commands ###
